[package]
name = "crust"
description = "Memory-safety focused Operating System"
homepage = "vortex-dev.com/Crust"
authors = ["Igor Alexey <igor@vortex-dev.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
